import type { LaunchCountryCode, TaxJurisdictionLevel } from './international';

/** INTL-1C가 제품 소유 DB 카탈로그에 적재하는 1차 하위 관할. */
export interface LaunchTaxRegionDefinition {
  countryCode: Extract<LaunchCountryCode, 'US' | 'CA'>;
  /** ISO 3166-2 코드. 국가 코드까지 포함한 불변 저장값이다. */
  regionCode: string;
  name: string;
  jurisdictionLevel: Extract<TaxJurisdictionLevel, 'state' | 'province'>;
}

export const LAUNCH_TAX_REGIONS = [
  { countryCode: 'US', regionCode: 'US-AL', name: 'Alabama', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-AK', name: 'Alaska', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-AZ', name: 'Arizona', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-AR', name: 'Arkansas', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-CA', name: 'California', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-CO', name: 'Colorado', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-CT', name: 'Connecticut', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-DE', name: 'Delaware', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-DC', name: 'District of Columbia', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-FL', name: 'Florida', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-GA', name: 'Georgia', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-HI', name: 'Hawaii', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-ID', name: 'Idaho', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-IL', name: 'Illinois', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-IN', name: 'Indiana', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-IA', name: 'Iowa', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-KS', name: 'Kansas', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-KY', name: 'Kentucky', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-LA', name: 'Louisiana', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-ME', name: 'Maine', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-MD', name: 'Maryland', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-MA', name: 'Massachusetts', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-MI', name: 'Michigan', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-MN', name: 'Minnesota', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-MS', name: 'Mississippi', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-MO', name: 'Missouri', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-MT', name: 'Montana', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-NE', name: 'Nebraska', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-NV', name: 'Nevada', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-NH', name: 'New Hampshire', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-NJ', name: 'New Jersey', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-NM', name: 'New Mexico', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-NY', name: 'New York', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-NC', name: 'North Carolina', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-ND', name: 'North Dakota', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-OH', name: 'Ohio', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-OK', name: 'Oklahoma', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-OR', name: 'Oregon', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-PA', name: 'Pennsylvania', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-RI', name: 'Rhode Island', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-SC', name: 'South Carolina', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-SD', name: 'South Dakota', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-TN', name: 'Tennessee', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-TX', name: 'Texas', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-UT', name: 'Utah', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-VT', name: 'Vermont', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-VA', name: 'Virginia', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-WA', name: 'Washington', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-WV', name: 'West Virginia', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-WI', name: 'Wisconsin', jurisdictionLevel: 'state' },
  { countryCode: 'US', regionCode: 'US-WY', name: 'Wyoming', jurisdictionLevel: 'state' },
  { countryCode: 'CA', regionCode: 'CA-AB', name: 'Alberta', jurisdictionLevel: 'province' },
  { countryCode: 'CA', regionCode: 'CA-BC', name: 'British Columbia', jurisdictionLevel: 'province' },
  { countryCode: 'CA', regionCode: 'CA-MB', name: 'Manitoba', jurisdictionLevel: 'province' },
  { countryCode: 'CA', regionCode: 'CA-NB', name: 'New Brunswick', jurisdictionLevel: 'province' },
  { countryCode: 'CA', regionCode: 'CA-NL', name: 'Newfoundland and Labrador', jurisdictionLevel: 'province' },
  { countryCode: 'CA', regionCode: 'CA-NS', name: 'Nova Scotia', jurisdictionLevel: 'province' },
  { countryCode: 'CA', regionCode: 'CA-NT', name: 'Northwest Territories', jurisdictionLevel: 'province' },
  { countryCode: 'CA', regionCode: 'CA-NU', name: 'Nunavut', jurisdictionLevel: 'province' },
  { countryCode: 'CA', regionCode: 'CA-ON', name: 'Ontario', jurisdictionLevel: 'province' },
  { countryCode: 'CA', regionCode: 'CA-PE', name: 'Prince Edward Island', jurisdictionLevel: 'province' },
  { countryCode: 'CA', regionCode: 'CA-QC', name: 'Quebec', jurisdictionLevel: 'province' },
  { countryCode: 'CA', regionCode: 'CA-SK', name: 'Saskatchewan', jurisdictionLevel: 'province' },
  { countryCode: 'CA', regionCode: 'CA-YT', name: 'Yukon', jurisdictionLevel: 'province' },
] as const satisfies readonly LaunchTaxRegionDefinition[];
